### ISSUE TITLE
Not working with beancount-mode

### ISSUE THREAD

**Issue by pvivire** [debanjum/company-ledger#2]
First, thanks for sharing company-ledger it will be very helpful.

While trying to use `master` with 'beancount-mode/master`,  I notice the conditional in
```
(prefix (and (or (bound-and-true-p beancount-mode)
                     (derived-mode-p 'ledger-mode))
                 (company-ledger--next-line-empty-p)
                (thing-at-point 'line t)))
```
fails because `beancount-mode` is not bound. Replacing with a mapped variable like `beancount-mode-map-prefix` works in my situation. Is there something more subtle I've missed?

**Comment by debanjum** [comment]
You're absolutely right. I can reproduce the issue and the fix you mentioned above on the latest beancount/beancount-mode@5be04a37d6a189f1680cb47d022a85d9faeba8fc. 

@pvivire do you want to submit a PR with the fix? If not, I'll update the company-ledger code with the fix soon myself.
Unsure how I missed seeing this issue earlier 😬. But thanks for notifying and apologize for the delayed reply!
