### ISSUE TITLE
Cannot complete at point

### ISSUE THREAD

**Issue by muhuk** [debanjum/company-ledger#4]
In a ledger file like this:

```
04/28 * Cash Expenditure
    Expenses:Dining                                     TRY3859.80
    Expenses:Other                                      TRY1725.20
    Assets:Cash


04/28 Cas
```

Company popup doesn't appear at all, and invoking `company-ledger` (when cursor is after the `s` of `Cas`), it results in `Cannot complete at point`.

`company-complete` says `No completion found`.

`company-diag` output:

```
Emacs 27.1 (x86_64-pc-linux-gnu) of 2023-02-23 on x86-conova-01
Company 0.9.13

company-backends: (company-ledger company-bbdb company-semantic company-cmake company-capf company-clang company-files
                (company-dabbrev-code company-gtags company-etags company-keywords)
                company-oddmuse company-dabbrev)

Used backend: company-ledger
Major mode: ledger-mode
Prefix: "04/28 Cas\n"
Completions: none
```

My [init.el](https://github.com/muhuk/emacs.d/blob/master/init.el) is like this:

```
(use-package company
  :ensure t
  :init
  (setq company-minimum-prefix-length 2
        company-selection-wrap-around t
        company-tooltip-align-annotations t)
  :config
  (global-company-mode))


(use-package company-ledger
  :ensure company
  :init
  (with-eval-after-load 'company
    (add-to-list 'company-backends 'company-ledger)))
```

Is there anything else I can do to debug this?

**Comment by debanjum** [comment]
Apologize for the delayed response. Eyeballing your sample ledger, it seems like you're using MM/DD format for date-time in your ledger. Is that a valid date format supported by ledger?

Company-ledger currently expects entries in `YYYY-MM-DD` or `YYYY/MM/DD` format for completion suggestions. This is why no suggestion maybe returned by it for your ledger.

I can make the `company-ledger-date-regexp` configurable. This will allow you to customize it to accept entries of form MM/DD. Does that work for your use-case?

**Comment by muhuk** [comment]
As for the `MM/DD` format, I have a `Y2023` line in the beginning of the file, all txns are attributed to this year. So I have 1 ledger file per year this way. You can see the relevant documentation [here](https://ledger-cli.org/doc/ledger3.html#index-year). Please note that my reports etc. all work.

Having said that; I just upgraded from Debian Bullseye to Bookworm, and my company seems to work again. I haven't done any heavy-duty entrying yet but I'm closing this ticket for now.

Thank you for the very useful package.
